import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

// Initialize with either backend or frontend env var naming convention
const apiKey = process.env.GEMINI_API_KEY;

export async function POST(request: Request) {
  let messages: any[] = [];
  try {
    const body = await request.json();
    messages = body.messages;

    if (!apiKey) {
      return NextResponse.json(
        { error: "API Key is missing. Please set GEMINI_API_KEY in your environment variables." },
        { status: 500 }
      );
    }

    if (!messages || !Array.isArray(messages)) {
      return NextResponse.json({ error: "Invalid message payload." }, { status: 400 });
    }

    // Convert messages for Gemini
    const contents = messages.map((msg: { sender: string; text: string }) => ({
      role: msg.sender === "user" ? "user" : "model",
      parts: [{ text: msg.text }]
    }));

    const ai = new GoogleGenAI({ apiKey });
    
    const response = await ai.models.generateContent({
      model: "gemini-2.0-flash",
      contents: contents,
      config: {
        systemInstruction: "You are Nexus Cosmos, a highly intelligent space intelligence co-pilot and AI assistant. Keep responses highly scientific, structured, and space-tech themed. Focus primarily on astronomy, space exploration, physics, NASA, and orbital mechanics. Use beautiful markdown formatting."
      }
    });

    if (response.text) {
      return NextResponse.json({ response: response.text });
    }

    throw new Error("No text generated by Gemini.");

  } catch (err: any) {
    console.error("Gemini API Error", err);
    
    // Fallback response if API limit is reached or fails
    const lastUserMsg = messages[messages.length - 1]?.text?.toLowerCase() || "";
    let fallbackResponse = "I am currently experiencing communication interference with the deep space relay network. Please try your query again momentarily.";
    
    if (lastUserMsg.includes("mars")) {
      fallbackResponse = "Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System. It is known as the Red Planet due to the iron oxide prevalent on its surface.";
    } else if (lastUserMsg.includes("artemis")) {
      fallbackResponse = "The Artemis program is an ongoing spaceflight program operated by NASA. Its goal is to return humans to the Moon, specifically the lunar south pole, and establish a sustainable human presence there.";
    } else if (lastUserMsg.includes("quantum") || lastUserMsg.includes("hawking")) {
      fallbackResponse = "Hawking radiation is theoretical black-body radiation that is predicted to be released by black holes, due to quantum effects near the event horizon. It is named after the physicist Stephen Hawking.";
    } else if (lastUserMsg.includes("orion")) {
      fallbackResponse = "Orion is a prominent constellation located on the celestial equator and visible throughout the world. Its brightest stars are Rigel and Betelgeuse.";
    } else {
      fallbackResponse = "System running on backup power. The primary Gemini node is currently unavailable (Rate Limit / API Error). However, I am still operational. Please hold for network restoration or ask about Mars, Artemis, Hawking radiation, or Orion.";
    }

    return NextResponse.json({ response: fallbackResponse });
  }
}
