import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

// Initialize with either backend or frontend env var naming convention
const apiKey = process.env.GEMINI_API_KEY || process.env.NEXT_PUBLIC_GEMINI_API_KEY;

export async function POST(request: Request) {
  try {
    const { messages } = await request.json();

    if (!apiKey) {
      return NextResponse.json(
        { error: "API Key is missing. Please set NEXT_PUBLIC_GEMINI_API_KEY in your environment variables." },
        { status: 500 }
      );
    }

    if (!messages || !Array.isArray(messages)) {
      return NextResponse.json({ error: "Invalid message payload." }, { status: 400 });
    }

    // Convert messages for Gemini
    const contents = messages.map((msg: { sender: string; text: string }) => ({
      role: msg.sender === "user" ? "user" : "model",
      parts: [{ text: msg.text }]
    }));

    const ai = new GoogleGenAI({ apiKey });
    
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: contents,
      config: {
        systemInstruction: "You are Nexus Cosmos, a highly intelligent space intelligence co-pilot and AI assistant. Keep responses highly scientific, structured, and space-tech themed. Focus primarily on astronomy, space exploration, physics, NASA, and orbital mechanics. Use beautiful markdown formatting."
      }
    });

    if (response.text) {
      return NextResponse.json({ response: response.text });
    }

    throw new Error("No text generated by Gemini.");

  } catch (err) {
    console.error("Gemini API Error", err);
    return NextResponse.json(
      { error: "TELEMETRY TRANSCEIVER FAILURE // CONNECTION TERMINATED" },
      { status: 500 }
    );
  }
}
